/**
 * JWTToken_Auth_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaperStatus } from './paperStatus';


export interface ScientificPaperEditDto { 
    id?: number;
    title?: string | null;
    _abstract?: string | null;
    journal?: string | null;
    isPublic?: boolean;
    status?: PaperStatus;
    keywords?: Array<string> | null;
}
export namespace ScientificPaperEditDto {
}


